const CATEGORIES = [
  { id: 'all', label: 'ALL', labelJp: 'すべて', icon: '✦' },
  { id: 'original', label: 'Original Dolls', labelJp: 'オリジナルドール', icon: '◈' },
  { id: 'character', label: 'Character Dolls', labelJp: 'キャラクタードール', icon: '◉' },
  { id: 'body', label: 'Bodies', labelJp: 'ボディ', icon: '◍' },
  { id: 'clothing', label: 'Clothing & Accessories', labelJp: '衣装・アクセサリー', icon: '◌' },
  { id: 'supplies', label: 'Supplies', labelJp: 'お手入れ用品', icon: '◎' },
];

const SERIES = {
  irisCollect: 'Iris Collect',
  irisCollectPetit: 'Iris Collect Petit',
  excute: 'Ex☆Cute',
  luminous: 'Luminous★Street',
  sairaaz: 'Sairaaz à la Mode',
  alvastaria: 'Alvastaria',
  sugarCups: 'Sugar★Cups',
  lilFairy: 'Lil\' Fairy',
  colorfulDreamin: 'Colorful★Dreamin\'',
  characterLine: 'Character Line',
};

const PRODUCTS = [
  {
    id: 1,
    name: 'Iris Collect Petit / Koharu "Waku Waku★Girl" ver.2.0',
    nameJp: 'アイリスコレクトプチ / 小春「わくわく★ガール」ver.2.0',
    series: SERIES.irisCollectPetit,
    category: 'original',
    scale: '1/6',
    price: 14300,
    releaseDate: '2026-04-25',
    status: 'in-stock',
    image: null,
    tags: ['new'],
    description: 'Koharu in her signature cheerful "Waku Waku" outfit, featuring a reworked face sculpt and updated body.',
  },
  {
    id: 2,
    name: 'Ex☆Cute / Miu "Dreamy Lolita" Pure White Edition',
    nameJp: 'エクスキュート / みう「ドリーミーロリータ」ピュアホワイト',
    series: SERIES.excute,
    category: 'original',
    scale: '1/6',
    price: 22000,
    releaseDate: '2026-03-15',
    status: 'restock',
    image: null,
    tags: ['restock', 'limited'],
    description: 'Limited re-release of the beloved Dreamy Lolita series, now in Pure White colorway.',
    restockDate: '2026-07-10',
    restockQty: 'Limited',
  },
  {
    id: 3,
    name: 'Alvastaria / Elfin "Moonlit Forest" Standard',
    nameJp: 'アルヴァスタリア / エルフィン「月夜の森」スタンダード',
    series: SERIES.alvastaria,
    category: 'original',
    scale: '1/6',
    price: 25300,
    releaseDate: '2026-05-10',
    status: 'pre-order',
    image: null,
    tags: ['pre-order'],
    preOrderDeadline: '2026-07-31',
    description: 'Fantasy-themed Elvish doll with hand-painted details and silk-blend outfit.',
  },
  {
    id: 4,
    name: 'Lil\' Fairy / Elf Erunoe "Tiny Wanderer"',
    nameJp: 'リルフェアリー / エルフ えるのえ「ちいさなさすらい人」',
    series: SERIES.lilFairy,
    category: 'original',
    scale: '1/12',
    price: 16500,
    releaseDate: '2026-02-20',
    status: 'out-of-stock',
    image: null,
    tags: [],
    description: 'Miniature fairy doll with delicate hand-crafted wings and thorn crown accessories.',
  },
  {
    id: 5,
    name: 'Sairaaz à la Mode / Yuzuha "Sweet Days"',
    nameJp: 'サイラアズアラモード / ゆずは「スイートデイズ」',
    series: SERIES.sairaaz,
    category: 'original',
    scale: '1/6',
    price: 12100,
    releaseDate: '2026-01-30',
    status: 'out-of-stock',
    image: null,
    tags: [],
    description: 'Casual sweet style coordinate with pastel tones and matching accessories.',
  },
  {
    id: 6,
    name: 'Sugar★Cups / Shocolara "Chocolat Robe"',
    nameJp: 'シュガーカップス / しょこらら「ショコラローブ」',
    series: SERIES.sugarCups,
    category: 'original',
    scale: '1/12',
    price: 28600,
    releaseDate: '2025-12-20',
    status: 'restock',
    image: null,
    tags: ['restock'],
    description: 'Chocolate-themed mini doll with intricate pastry-inspired dress and accessories.',
    restockDate: '2026-07-15',
    restockQty: 'Very Limited',
  },
  {
    id: 7,
    name: 'Colorful★Dreamin\' / Chiika "Rainbow Circus"',
    nameJp: 'カラフルドリーミン / ちいか「レインボーサーカス」',
    series: SERIES.colorfulDreamin,
    category: 'original',
    scale: '1/6',
    price: 19800,
    releaseDate: '2026-06-01',
    status: 'in-stock',
    image: null,
    tags: ['new'],
    description: 'Vibrant circus performer outfit with rainbow gradient hair and acrobatic accessories.',
  },
  {
    id: 8,
    name: 'Luminous★Street / Leo "Tender Circus"',
    nameJp: 'ルミナスストリート / レオ「テンダーサーカス」',
    series: SERIES.luminous,
    category: 'original',
    scale: '1/6',
    price: 22000,
    releaseDate: '2025-11-25',
    status: 'out-of-stock',
    image: null,
    tags: [],
    description: 'Street fashion meets circus aesthetic — bold patterns and layered accessories.',
  },
  {
    id: 9,
    name: 'Iris Collect / Ruchiru "Flowers of Serenity"',
    nameJp: 'アイリスコレクト / るちる「静寂の花々」',
    series: SERIES.irisCollect,
    category: 'original',
    scale: '1/6',
    price: 25300,
    releaseDate: '2025-10-15',
    status: 'out-of-stock',
    image: null,
    tags: [],
    description: 'Elegant floral-themed coordinate with embroidered details and silk ribbon accents.',
  },
  {
    id: 10,
    name: 'Kazuo Kina School Uniform Series / Yui',
    nameJp: '仲夏ユニフォームシリーズ / 唯',
    series: SERIES.characterLine,
    category: 'character',
    scale: '1/6',
    price: 19800,
    releaseDate: '2025-09-20',
    status: 'out-of-stock',
    image: null,
    tags: [],
    description: 'School uniform collaboration featuring authentic-style sailor outfit.',
  },
  {
    id: 11,
    name: 'Kazuo Kina School Uniform Series / Yukari (1/3)',
    nameJp: '仲夏ユニフォームシリーズ / ゆかり (1/3)',
    series: SERIES.characterLine,
    category: 'character',
    scale: '1/3',
    price: 68200,
    releaseDate: '2025-09-20',
    status: 'restock',
    image: null,
    tags: ['restock', 'limited'],
    description: '1/3 scale premium school uniform collaboration — highly detailed and collectible.',
    restockDate: '2026-08-01',
    restockQty: 'Limited (3 units)',
  },
  {
    id: 12,
    name: 'Pure Neemo Body S / Peach Skin (New Mold)',
    nameJp: 'ピュアニーモボディS / ピーチスキン（新金型）',
    series: 'Pure Neemo',
    category: 'body',
    scale: '1/6',
    price: 8800,
    releaseDate: '2026-04-01',
    status: 'in-stock',
    image: null,
    tags: ['new'],
    description: 'Updated Pure Neemo S body with improved joint articulation and softer skin texture.',
  },
  {
    id: 13,
    name: 'Pure Neemo Body XS / Natural (Whiter Tone)',
    nameJp: 'ピュアニーモボディXS / ナチュラル（明るめトーン）',
    series: 'Pure Neemo',
    category: 'body',
    scale: '1/6',
    price: 7700,
    releaseDate: '2026-05-15',
    status: 'pre-order',
    image: null,
    tags: ['pre-order'],
    preOrderDeadline: '2026-07-20',
    description: 'XS body variant in lighter natural tone, compatible with all 1/6 Azone heads.',
  },
  {
    id: 14,
    name: 'Floral Lace Dress Set / Ivory & Sage',
    nameJp: 'フローラルレースドレスセット / アイボリー&セージ',
    series: 'Coordinate Collection',
    category: 'clothing',
    scale: '1/6',
    price: 5500,
    releaseDate: '2026-03-01',
    status: 'in-stock',
    image: null,
    tags: [],
    description: 'Delicate floral lace dress with matching accessories — fits 1/6 Pure Neemo M/S.',
  },
  {
    id: 15,
    name: 'Gothic Velvet Coordinate / Midnight Black',
    nameJp: 'ゴシックベルベットコーディネート / ミッドナイトブラック',
    series: 'Coordinate Collection',
    category: 'clothing',
    scale: '1/3',
    price: 12100,
    releaseDate: '2026-06-10',
    status: 'in-stock',
    image: null,
    tags: ['new'],
    description: '1/3 scale gothic coordinate with velvet bodice, layered skirt, and silver chain accessories.',
  },
  {
    id: 16,
    name: 'Azone Doll Stand Set (3-pack) / Clear',
    nameJp: 'アゾンドールスタンドセット（3個組）/ クリア',
    series: 'Supplies',
    category: 'supplies',
    scale: 'Universal',
    price: 2200,
    releaseDate: '2026-01-10',
    status: 'in-stock',
    image: null,
    tags: [],
    description: 'Universal clear display stands compatible with 1/6 and 1/12 scale dolls.',
  },
  {
    id: 17,
    name: 'Ex☆Cute / Aika "Starry Night" Anniversary Edition',
    nameJp: 'エクスキュート / あいか「星夜」アニバーサリーエディション',
    series: SERIES.excute,
    category: 'original',
    scale: '1/6',
    price: 33000,
    releaseDate: '2026-07-20',
    status: 'pre-order',
    image: null,
    tags: ['pre-order', 'limited', 'new'],
    preOrderDeadline: '2026-08-15',
    description: 'Anniversary edition celebrating 20 years of Ex☆Cute. Starry night dress with celestial accessories.',
  },
  {
    id: 18,
    name: 'Alvastaria / Elrika "Crimson Tempest" Limited',
    nameJp: 'アルヴァスタリア / エルリカ「紅蓮の嵐」限定版',
    series: SERIES.alvastaria,
    category: 'original',
    scale: '1/6',
    price: 29700,
    releaseDate: '2026-07-05',
    status: 'in-stock',
    image: null,
    tags: ['new', 'limited'],
    description: 'Dramatic crimson battle costume with dynamic hair styling and weapon accessories.',
  },
];

const NOTIFICATIONS = [
  {
    id: 1,
    productId: 2,
    type: 'restock',
    message: 'Ex☆Cute / Miu "Dreamy Lolita" is back in stock — limited units!',
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    read: false,
  },
  {
    id: 2,
    productId: 6,
    type: 'restock',
    message: 'Sugar★Cups / Shocolara restock confirmed for July 15',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    read: false,
  },
  {
    id: 3,
    productId: 11,
    type: 'restock',
    message: 'Kazuo Kina / Yukari 1/3 limited restock — only 3 units available',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
    read: true,
  },
  {
    id: 4,
    productId: 17,
    type: 'preorder',
    message: 'Pre-order open: Ex☆Cute "Starry Night" Anniversary Edition',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    read: true,
  },
];
